CREATE TABLE users
(id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
 first_name VARCHAR(30) NOT NULL,
 last_name VARCHAR(30) NOT NULL,
 username VARCHAR(30) NOT NULL UNIQUE,
 email VARCHAR(30) NOT NULL,
 password VARCHAR(300) NOT NULL,
 admin BOOLEAN
 );

